version: '3'

services:
  my_app:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./cronjobs:/etc/cron.d/cronjobs
      - ./:/app/
    command: /bin/bash -c "cron && tail -f /var/log/cron.log"